models:
  - name: stg_localbike__brands
    description: "This model contains information about brands of bike"
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand"
        tests:
            - unique
            - not_null
      - name: brand_name
        description: "name of brand"

  - name: stg_localbike__categories
    description: "This model contains information about categories of bike"
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category"
        tests:
            - unique
            - not_null
      - name: category_name
        description: "name of category"


  - name: stg_localbike__customers
    description: "This model contains information about customers"
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer"
        tests:
            - unique
            - not_null
      - name: customer_first_name
        description: "customer first name"
      - name: customer_last_name
        description: "customer last name"
      - name: customer_phone
        description: "customer phone number"
      - name: customer_email
        description: "customer email"
      - name: customer_street
        description: "customer street"
      - name: customer_city
        description: "customer city"
      - name: customer_state
        description: "customer state"
      - name: customer_zip_code
        description: "customer zip code"

  - name: stg_localbike__orders
    description: "This model contains information about orders"
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order"
        tests:
            - unique
            - not_null
      - name: customer_id
        description: "customer id, foreign key of table customers"
        tests:
          - relationships:
              arguments:
                to: ref('stg_localbike__customers')
                field: customer_id
                config:
                  severity: warn  # optionnel
      - name: order_status
        description: "status of order"
        tests:
          - accepted_values:
              arguments:
                values: [1,2,3,4]
                quote: false
      - name: order_date
        description: "order date"
      - name: required_date
        description: "required date"
      - name: shipped_date
        description: "shipped date"
      - name: store_id
        description: "store id, foreign key of table stores"
        tests:
          - relationships:
              arguments:
                to: ref('stg_localbike__stores')
                field: store_id
                config:
                  severity: warn  # optionnel
      - name: staff_id
        description: "staff id, foreign key of table staff"
        tests:
          - relationships:
              arguments:
                to: ref('stg_localbike__staffs')
                field: staff_id
                config:
                  severity: warn  # optionnel
      
  - name: stg_localbike__products
    description: "This model contains information about products"
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product"
        tests:
            - unique
            - not_null
      - name: product_name
        description: "product name"
      - name: brand_id
        description: "brand id, foreign key of table brand"
        tests:
          - relationships:
              arguments:
                to: ref('stg_localbike__brands')
                field: brand_id
              config:
                severity: warn  # optionnel
      - name: category_id
        description: "brand id, foreign key of table brand"
        tests:
          - relationships:
              arguments:
                to: ref('stg_localbike__categories')
                field: category_id
              config:
                severity: warn  # optionnel
      - name: model_year
        description: "model year"
      - name: list_price
        description: "price of product"  
        tests:
          - not_null:
              config:
                where: "list_price > 0" 

  - name: stg_localbike__staffs
    description: "This model contains information about staffs"
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each employee"
        tests:
            - unique
            - not_null
      - name: staff_first_name
        description: "employee first name"
      - name: staff_last_name
        description: "employee last name"
      - name: staff_emai
        description: "employee email"
      - name: staff_phone
        description: "employee phone"
      - name: staff_active
        description: "the employee is still present"
        tests:
          - accepted_values:
              arguments:
                values: [0,1]
                quote: false
      - name: store_id
        description: "store id, foreign key of table stores"
        tests:
          - relationships:
              arguments:
                to: ref('stg_localbike__stores')
                field: store_id
                config:
                  severity: warn  # optionnel
      - name: manager_id
        description: "manager id, the employee is manager or no"

  - name: stg_localbike__stocks
    description: "This model contains information about stocks"
    columns:
      - name: stock_id
        description: "Primary key, concatenation of columns store_id and product_id to have unique key"
        tests:
            - unique
            - not_null
      - name: store_id
        description: "store id, foreign key of table stores"
        tests:
          - relationships:
              arguments:
                to: ref('stg_localbike__stores')
                field: store_id
                config:
                  severity: warn  # optionnel
      - name: product_id
        description: "product id, foreign key of table products"
        tests:
          - relationships:
              arguments:
                to: ref('stg_localbike__products')
                field: product_id
                config:
                  severity: warn  # optionnel
      - name: stock_quantity
        description: "stock quantity"
        tests:
          - not_null

  - name: stg_localbike__order_items
    description: "This model contains information about order items"
    columns:
      - name: order_item_id
        description: "Primary key, concatenation of columns order_id and item_id to have unique key"
        tests:
            - unique
            - not_null
      - name: order_id
        description: "order id, foreign key of table orders"
        tests:
          - relationships:
              arguments:
                to: ref('stg_localbike__orders')
                field: order_id
                config:
                  severity: warn  # optionnel
      - name: item_id
        description: "item id"
      - name: product_id
        description: "product id, foreign key of table products"
        tests:
          - relationships:
              arguments:
                to: ref('stg_localbike__products')
                field: product_id
                config:
                  severity: warn  # optionnel
      - name: item_quantity
        description: "quantity of items in order"
        tests:
          - not_null:
              config:
                where: "item_quantity > 0" 


